sudo: required
services:
  - docker

before_install:
  - docker build -t ederob/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ederob/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-824824576534"
  bucket_path: "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master
    
    